### ISSUE TITLE
SOURCES

### ISSUE THREAD

**Issue by evheniu** [monosans/proxy-scraper-checker#1]
Getting https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt
Getting https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt
Getting https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt   
Getting https://raw.githubusercontent.com/mmpx12/proxy-list/master/https.txt  
Getting https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt
Getting https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt
Getting https://api.proxyscrape.com/v2/?request=getproxies&protocol=http     
Checking proxies...
Traceback (most recent call last):
  File "d:/proxy-scraper-checker-main/main.py", line 70, in <module>
    t.start()
  File "C:\Python38-32\lib\threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by monosans** [comment]
Is the problem still present?

**Comment by evheniu** [comment]
> Is the problem still present?

Great, now it's work fine!
