### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by l516q581** [monosans/proxy-scraper-checker#10]
C:\Users\admini>D:\proxy\proxy-scraper-checker-main\proxy-scraper-checker-main\main.py
  File "D:\proxy\proxy-scraper-checker-main\proxy-scraper-checker-main\main.py", line 27
    def __init__(self, socket_address: str, ip: str) -> None:
                                     ^
SyntaxError: invalid syntax

**Comment by monosans** [comment]
Works for me.
