### ISSUE TITLE
ERROR: Could not build wheels for frozenlist, multidict, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Malik1577** [monosans/proxy-scraper-checker#110]
I am receiving this error when running the start file on windows, even in administrator. Please can someone guide me to fix this to be able to run the tool. 

![error](https://github.com/monosans/proxy-scraper-checker/assets/152777565/8eee8bfe-345f-46ad-b1c6-b0dc53844351)
![Error1](https://github.com/monosans/proxy-scraper-checker/assets/152777565/1136e40e-d220-4d14-a50c-847fd2792e9c)
![error 2](https://github.com/monosans/proxy-scraper-checker/assets/152777565/cef55943-e1d4-4fcc-a9c2-8dbc6479fff1)

**Comment by monosans** [comment]
Related issues: <https://github.com/aio-libs/frozenlist/issues/541>, <https://github.com/aio-libs/multidict/issues/887>
