### ISSUE TITLE
Proxies are invalid

### ISSUE THREAD

**Issue by sequencerr** [monosans/proxy-scraper-checker#117]
Using your https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt .
None of them working (for me)
They are all mocking the response for service to check for IPs (Which your [http://ip-api.com/json](https://github.com/monosans/proxy-scraper-checker/blob/eeca39b8f5325fd4f77ed1a7906730d63ccfe11e/proxy_scraper_checker/constants.py#L7) website is). I even got (with one of the proxies) response just with `ip` at http://httpbin.org/get (which supposed to send back request object & headers)
Try using https://www.thecolorapi.com/scheme?hex=24B1E0&mode=triad&count=1 first (some public api)

**Comment by monosans** [comment]
If you run into this problem, you can always change the [CheckWebsite setting](https://github.com/monosans/proxy-scraper-checker/blob/eeca39b8f5325fd4f77ed1a7906730d63ccfe11e/config.ini#L24). I plan to rewrite the code to use httpbin.org and a local geolocation database, but I don't have time for that yet.

**Comment by sequencerr** [comment]
I assume, if you have VPS (which I don't) you could exclude usage of any 3rd-party services. Not sure how to be done specifically in python. Socket.remoteAddress, but all checkers using x-forwarded-for or origin headers (not sure which and why)

**Comment by Foxtrod89** [comment]
Can't figure out how to check **auth socks5** proxies.

**Comment by sequencerr** [comment]
you mean proxies with auth? idk how for your programing language goes, but for nodejs we use socks-proxy-agent lib and url specification for providing auth credentials with proxy ip:port

**Comment by monosans** [comment]
Fixed in <https://github.com/monosans/proxy-scraper-checker/commit/e4047e16aeb9800bbaa91db429c9bd2cef5e0583>.

**Comment by sequencerr** [comment]
> Fixed in [e4047e1](https://github.com/monosans/proxy-scraper-checker/commit/e4047e16aeb9800bbaa91db429c9bd2cef5e0583).

Not really) Half of the https://github.com/monosans/proxy-list/blob/main/proxies/all.txt are duplicates. 
I guess you have reasons, but why would you use httpbin while you have your own vps?

**Comment by monosans** [comment]
> Half of the https://github.com/monosans/proxy-list/blob/main/proxies/all.txt are duplicates.

Thanks for bringing this to my attention. It was a bug, I fixed it.

> why would you use httpbin while you have your own vps?

I don't want to put a strain on my VPS network because I have other projects running there.
