### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by kittenvr** [monosans/proxy-scraper-checker#168]
**Describe the bug**
when i install and extract the proxy scraper checker zip for windows windows antivirus deletes the exe and virustotal says this 
![image](https://github.com/monosans/proxy-scraper-checker/assets/103120356/72d67ecd-7c35-47fb-ad46-f4f14d7c9e43)
https://www.virustotal.com/gui/file/68de4a7bad776845866ebb56d3e599694054bd309f82f9032c41523ca95a3c8d?nocache=1

**Technical information**

- OS:
- Python version: none
- Output of `pip freeze`: none

```python
Put the output here.
```

**Comment by monosans** [comment]
https://github.com/Nuitka/Nuitka/issues/2495#issuecomment-1762836583

**Comment by monosans** [comment]
Fixed in https://github.com/monosans/proxy-scraper-checker/commit/ab1aa8c3fbc68d33652016041d04f0cc047404c4
