### ISSUE TITLE
Authentic proxy sources

### ISSUE THREAD

**Issue by realtechspecs** [monosans/proxy-scraper-checker#2]
Can you add more authentic proxy sources like

1. https://openproxy.space/list
2. http://free-proxy.cz/en
3. https://proxyscrape.com/free-proxy-list
4. http://www.freeproxylists.net/
5. https://www.sslproxies.org/
6. http://www.gatherproxy.com/
7. https://www.proxy-list.download/
8. https://www.proxynova.com/proxy-server-list

**Comment by monosans** [comment]
Hi!

As of now, `proxy-scraper-checker` only supports fetching proxies from plain text (although this may change in future).

All of these sites, with the exception of `https://proxyscrape.com` (which is already present in the default config), don't provide plain text proxies for free.

So, none of these sites can be used without major changes to the `proxy-scraper-checker` code.
