### ISSUE TITLE
Checking Download / Upload Speed

### ISSUE THREAD

**Issue by AIQubeAI** [monosans/proxy-scraper-checker#20]
Hello,

would it be possible for you, to add a function, which checks the actual download and upload speed from the proxys? 
Like this you could always take the fastest proxy from the output and use it.

Thank you

**Comment by monosans** [comment]
Hi,

there's already `SortBySpeed` option in the config file.

https://github.com/monosans/proxy-scraper-checker/blob/72b4b84005af0fc927288915f597ae099c0e3e7c/config.ini#L12

**Comment by AIQubeAI** [comment]
If i see it right, it will just sort the "speed" by timeout of the connection. But checking the actual download / upload speed, like a real speedtest would do, would be much better right?

For example download a test sample file from https://testfiledownload.com/ and calculate the mbps

**Comment by monosans** [comment]
> For example download a test sample file from [testfiledownload.com](https://testfiledownload.com/) and calculate the mbps

Opening a website is also a file download. More precisely, downloading an HTML file.
