### ISSUE TITLE
Failed to build aiohttp brotli wheels on python 3.11.9

### ISSUE THREAD

**Issue by nizarhrz** [monosans/proxy-scraper-checker#214]
**Describe the bug**

**Technical information**

- OS: android 10
- Python version:
- 3.11.9
- Output of `pip freeze`:
clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      error: command '/data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
  Building wheel for brotli (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for brotli (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating bin
      creating bin/lib.linux-armv7l-cpython-311
      copying python/brotli.py -> bin/lib.linux-armv7l-cpython-311
      running build_ext
      <string>:70: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
      building '_brotli' extension
      creating bin/temp.linux-armv7l-cpython-311
      creating bin/temp.linux-armv7l-cpython-311/python
      creating bin/temp.linux-armv7l-cpython-311/c
      creating bin/temp.linux-armv7l-cpython-311/c/common
      creating bin/temp.linux-armv7l-cpython-311/c/dec
      creating bin/temp.linux-armv7l-cpython-311/c/enc
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c python/_brotli.c -o bin/temp.linux-armv7l-cpython-311/python/_brotli.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/constants.c -o bin/temp.linux-armv7l-cpython-311/c/common/constants.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/context.c -o bin/temp.linux-armv7l-cpython-311/c/common/context.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/dictionary.c -o bin/temp.linux-armv7l-cpython-311/c/common/dictionary.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/platform.c -o bin/temp.linux-armv7l-cpython-311/c/common/platform.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/shared_dictionary.c -o bin/temp.linux-armv7l-cpython-311/c/common/shared_dictionary.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/transform.c -o bin/temp.linux-armv7l-cpython-311/c/common/transform.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/dec/bit_reader.c -o bin/temp.linux-armv7l-cpython-311/c/dec/bit_reader.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/dec/decode.c -o bin/temp.linux-armv7l-cpython-311/c/dec/decode.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/dec/huffman.c -o bin/temp.linux-armv7l-cpython-311/c/dec/huffman.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/dec/state.c -o bin/temp.linux-armv7l-cpython-311/c/dec/state.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/backward_references.c -o bin/temp.linux-armv7l-cpython-311/c/enc/backward_references.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/backward_references_hq.c -o bin/temp.linux-armv7l-cpython-311/c/enc/backward_references_hq.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/bit_cost.c -o bin/temp.linux-armv7l-cpython-311/c/enc/bit_cost.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/block_splitter.c -o bin/temp.linux-armv7l-cpython-311/c/enc/block_splitter.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/brotli_bit_stream.c -o bin/temp.linux-armv7l-cpython-311/c/enc/brotli_bit_stream.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/cluster.c -o bin/temp.linux-armv7l-cpython-311/c/enc/cluster.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/command.c -o bin/temp.linux-armv7l-cpython-311/c/enc/command.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/compound_dictionary.c -o bin/temp.linux-armv7l-cpython-311/c/enc/compound_dictionary.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/compress_fragment.c -o bin/temp.linux-armv7l-cpython-311/c/enc/compress_fragment.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/compress_fragment_two_pass.c -o bin/temp.linux-armv7l-cpython-311/c/enc/compress_fragment_two_pass.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/dictionary_hash.c -o bin/temp.linux-armv7l-cpython-311/c/enc/dictionary_hash.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/encode.c -o bin/temp.linux-armv7l-cpython-311/c/enc/encode.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/encoder_dict.c -o bin/temp.linux-armv7l-cpython-311/c/enc/encoder_dict.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/entropy_encode.c -o bin/temp.linux-armv7l-cpython-311/c/enc/entropy_encode.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/fast_log.c -o bin/temp.linux-armv7l-cpython-311/c/enc/fast_log.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/histogram.c -o bin/temp.linux-armv7l-cpython-311/c/enc/histogram.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/literal_cost.c -o bin/temp.linux-armv7l-cpython-311/c/enc/literal_cost.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/memory.c -o bin/temp.linux-armv7l-cpython-311/c/enc/memory.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/metablock.c -o bin/temp.linux-armv7l-cpython-311/c/enc/metablock.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/static_dict.c -o bin/temp.linux-armv7l-cpython-311/c/enc/static_dict.o
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/home/proxy-scraper-checker/.venv/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/utf8_util.c -o bin/temp.linux-armv7l-cpython-311/c/enc/utf8_util.o
      arm-linux-androideabi-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -march=armv7-a -Wl,--fix-cortex-a8 -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib bin/temp.linux-armv7l-cpython-311/python/_brotli.o bin/temp.linux-armv7l-cpython-311/c/common/constants.o bin/temp.linux-armv7l-cpython-311/c/common/context.o bin/temp.linux-armv7l-cpython-311/c/common/dictionary.o bin/temp.linux-armv7l-cpython-311/c/common/platform.o bin/temp.linux-armv7l-cpython-311/c/common/shared_dictionary.o bin/temp.linux-armv7l-cpython-311/c/common/transform.o bin/temp.linux-armv7l-cpython-311/c/dec/bit_reader.o bin/temp.linux-armv7l-cpython-311/c/dec/decode.o bin/temp.linux-armv7l-cpython-311/c/dec/huffman.o bin/temp.linux-armv7l-cpython-311/c/dec/state.o bin/temp.linux-armv7l-cpython-311/c/enc/backward_references.o bin/temp.linux-armv7l-cpython-311/c/enc/backward_references_hq.o bin/temp.linux-armv7l-cpython-311/c/enc/bit_cost.o bin/temp.linux-armv7l-cpython-311/c/enc/block_splitter.o bin/temp.linux-armv7l-cpython-311/c/enc/brotli_bit_stream.o bin/temp.linux-armv7l-cpython-311/c/enc/cluster.o bin/temp.linux-armv7l-cpython-311/c/enc/command.o bin/temp.linux-armv7l-cpython-311/c/enc/compound_dictionary.o bin/temp.linux-armv7l-cpython-311/c/enc/compress_fragment.o bin/temp.linux-armv7l-cpython-311/c/enc/compress_fragment_two_pass.o bin/temp.linux-armv7l-cpython-311/c/enc/dictionary_hash.o bin/temp.linux-armv7l-cpython-311/c/enc/encode.o bin/temp.linux-armv7l-cpython-311/c/enc/encoder_dict.o bin/temp.linux-armv7l-cpython-311/c/enc/entropy_encode.o bin/temp.linux-armv7l-cpython-311/c/enc/fast_log.o bin/temp.linux-armv7l-cpython-311/c/enc/histogram.o bin/temp.linux-armv7l-cpython-311/c/enc/literal_cost.o bin/temp.linux-armv7l-cpython-311/c/enc/memory.o bin/temp.linux-armv7l-cpython-311/c/enc/metablock.o bin/temp.linux-armv7l-cpython-311/c/enc/static_dict.o bin/temp.linux-armv7l-cpython-311/c/enc/utf8_util.o -L/data/data/com.termux/files/usr/lib -lpython3.11 -o bin/lib.linux-armv7l-cpython-311/_brotli.cpython-311.so
      clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      error: command '/data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for brotli
Successfully built proxy-scraper-checker
Failed to build aiohttp brotli
ERROR: Could not build wheels for aiohttp, brotli, which is required to install pyproject.toml-based projects
…host ~/proxy-scraper-checker (main) [1]>
```python
Put the output here.
```

**Comment by monosans** [comment]
Download Termux from [F-Droid](https://f-droid.org/en/packages/com.termux/). [Don't download it from Google Play](https://github.com/termux/termux-app#google-play-store-deprecated).

**Comment by nizarhrz** [comment]
> Download Termux from [F-Droid](https://f-droid.org/en/packages/com.termux/). [Don't download it from Google Play](https://github.com/termux/termux-app#google-play-store-deprecated).

 .
# i already download it from fdroid the latest version ... python 3.11.9 have seeious problem with project.toml based ....  they dont have have wheels for modules or something ...

**Comment by wtfc2** [comment]
Update to 3.12, tested with it and it works like a charm.

**Comment by monosans** [comment]
https://github.com/termux/termux-packages/issues/20039
