### ISSUE TITLE
loading source list from local file

### ISSUE THREAD

**Issue by KourosZanbouri** [monosans/proxy-scraper-checker#22]
I tried to load a source list ( local file with .txt format, and same data format ) but the checker wont work...

is there a specific way to do this?

**Comment by monosans** [comment]
Hi. This is not currently supported, although this may change in the future. Have a good day.

**Comment by Zane36** [comment]
Hi, in subsequent updates was there an implementation of this feature or was it put aside permanently?

**Comment by monosans** [comment]
Added support for this in <https://github.com/monosans/proxy-scraper-checker/commit/e4047e16aeb9800bbaa91db429c9bd2cef5e0583>.
