### ISSUE TITLE
user agent

### ISSUE THREAD

**Issue by rafalohaki** [monosans/proxy-scraper-checker#26]
when i debuged connection , i found out that custom user agent function is not working
![image](https://user-images.githubusercontent.com/20607107/182533194-86e179c0-da50-4fe1-83cc-0263f6f35e99.png)

did user agent scraping too for making it sure there is problem from checker side
![image](https://user-images.githubusercontent.com/20607107/182536244-797173c6-2840-48cb-869a-d8d421886383.png)

api working properly(using browser):
![image](https://user-images.githubusercontent.com/20607107/182536298-d5e7322c-8cce-4561-bc8b-c66980898185.png)

**Comment by monosans** [comment]
The custom user agent is used only for fetching sources, and for checking proxy the default one is used.
