### ISSUE TITLE
how to stop ConnectionResetError from appearing in the console?

### ISSUE THREAD

**Issue by JohhoA** [monosans/proxy-scraper-checker#28]
not that big of a deal but its kinda annoying having these errors pop up when checking the proxies, how can i stop em from showing up?
![image](https://user-images.githubusercontent.com/66090923/183271202-e2f05da9-1371-4dad-8c03-d0e3c51a4042.png)

**Comment by monosans** [comment]
Honestly, I don't know why this happens, but it only happens on Windows. I have not yet been able to find a solution to this problem. You can try setting less `MaxConnections`, maybe this will improve the situation. In general, these errors can be ignored.

**Comment by JohhoA** [comment]
it seems to error when a proxy closes connection or something like that, but yeah it doesnt really affect the program itself its just kinda annying to see them pop up, anyways thanks for the response.
