### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by ImInTheICU** [monosans/proxy-scraper-checker#29]
New sources would be nice, kinda hidden github lists or hidden proxy website's would be nice to add to the sources tab.
For socks theres not many sources

**Comment by monosans** [comment]
It would be a good idea for you to provide links to additional sources.

**Comment by ImInTheICU** [comment]
> It would be a good idea for you to provide links to additional sources.

Ile add some soon, also this is very tanky on memory and causing memory problems with my hosting (I have enquired this into a bot)
