### ISSUE TITLE
Python 3.6: ImportError: cannot import name 'Literal'

### ISSUE THREAD

**Issue by adrianmihalko** [monosans/proxy-scraper-checker#3]
typing.Literal is only available from Python 3.8 and up.

**Using Literal in Python 3.8 and later**

`from typing import Literal`

**Using Literal in all Python versions**

Literal was added to typing.py in 3.8, but you can use Literal in older versions anyway.

First install `typing_extensions` (pip install typing_extensions) and then

`from typing_extensions import Literal`

This approach is supposed to work also in Python 3.8 and later.

More info here: https://stackoverflow.com/questions/61206437/importerror-cannot-import-name-literal-from-typing?noredirect=1&lq=1

**Comment by monosans** [comment]
@adrianmihalko, thank you.
