### ISSUE TITLE
Get proxies from source [BUG]

### ISSUE THREAD

**Issue by ImInTheICU** [monosans/proxy-scraper-checker#30]
![image](https://user-images.githubusercontent.com/111275373/188913389-4d5d4e40-1405-4dc5-bc80-106ebd0d4ce4.png)
whats up with this, i get very low yields because most of the sources get this error...

**Comment by ImInTheICU** [comment]
( * Website down? )
(* Not connecting? )

Im not sure what it could be

**Comment by monosans** [comment]
It would be nice if you could provide the full output of the terminal.

Do the sources that give an error open in the browser?

**Comment by ImInTheICU** [comment]
> It would be nice if you could provide the full output of the terminal.
> 
> Do the sources that give an error open in the browser?

Havent debugged yet, but in console I get https://...com | Error

**Comment by ImInTheICU** [comment]
And sometimes its almost 80% of the sources

**Comment by monosans** [comment]
Try opening these sources in your browser.

**Comment by ImInTheICU** [comment]
> Try opening these sources in your browser.

Locally it works but im hosting on a Linux Based server.

**Comment by ImInTheICU** [comment]
![image](https://user-images.githubusercontent.com/111275373/188915564-9c89fb8c-5f0b-4dfe-b239-edd17eb4d83e.png)
Theses are my gameserver's config for requests

**Comment by monosans** [comment]
There is a 99% chance that you just have a network problem. On my home computer and on my server (which runs <https://github.com/monosans/proxy-list>) all sources work.

Closing the issue.
