### ISSUE TITLE
need only that's proxy get response from youtube.com

### ISSUE THREAD

**Issue by nikhilc890** [monosans/proxy-scraper-checker#39]
**Is your feature request related to a problem? Please describe.**
can u plz add this feature to get only that's proxy successful responses from youtube.com/

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by monosans** [comment]
Hi! There is no such possibility at the moment. By making some changes in the code, it is possible to achieve that proxies are checked on the desired site, but in this case it will be impossible to determine the anonymity and geolocation of the proxy. I'm currently rewriting the script from scratch in another language, I'll think about adding this feature in the new version.

**Comment by nikhilc890** [comment]
ok.. thanks for reply...if u added this feature in your upcoming script its very useful for youtube bots...
