### ISSUE TITLE
When specifying a custom CheckWebsite how does it determine success or failure?  Where do you define the success title?

### ISSUE THREAD

**Issue by frozen-cdn** [monosans/proxy-scraper-checker#54]
I currently am an OpenBullet2 user which allows of mass proxy checking, validating, etc. and also allows custom websites to check them on.  However, in OB2, success is defined by the TITLE it fetches, which you specify.  This means it will not include cloudflare blocked proxies for example, because those will not return the proper HTML title.

How is this app determining success or failure when a CheckWebsite = field is defined inside the config file?

And is there a way to ensure it only is successful upon a certain string?  So that way CloudFlare filtered results are not marked as working?

**Comment by monosans** [comment]
It checks that the HTTP status response code is less than 400. When Cloudflare blocks the request, it returns a status code of 403, and therefore the proxy will be considered down.

**Comment by frozen905** [comment]
Oh, ok, I see!  Thank you.  I see most commonly CloudFlare error 1000-series lately, like 1020 and so on.  I will experiment with this again now

**Comment by monosans** [comment]
> I see most commonly CloudFlare error 1000-series lately, like 1020 and so on. I will experiment with this again now

HTTP status codes and Cloudflare error codes are different things.
