### ISSUE TITLE
Possible to scrape proxies without checking them?

### ISSUE THREAD

**Issue by paynemux** [monosans/proxy-scraper-checker#7]
Thank you first of all.

I wonder if possible to save proxies before checking them. I mean is there any way to have 3 additional outputs like http_pre.txt sock4_pre.txt and socks5_pre.txt?

**Comment by monosans** [comment]
Hey!

You can skip the proxy check by commenting one line of code. Find `await self.check_all_proxies()` and comment it by adding `#` before it.

The result should look like this: 

```python
...
    async def main(self) -> None:
        await self.fetch_all_sources()
        #await self.check_all_proxies()
...
```

**Comment by paynemux** [comment]
You one of a kind @monosans!
Thank you again.
