### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by FreddyCruger** [monosans/proxy-scraper-checker#93]
**Describe the bug**
when I run the start.bat script, an error occurs

**Technical information**

- OS: Windows 11 22000.2538
- Python version: 3.12.0
- Output of `pip freeze`:
- pip freeze
markdown-it-py==3.0.0
mdurl==0.1.2
Pygments==2.16.1
rich==13.6.0
setuptools==68.2.2
wheel==0.41.2

Log from console:
C:\proxy>py -m pip install -U --no-cache-dir --disable-pip-version-check pip setuptools wheel
Requirement already satisfied: pip in c:\users\root\appdata\local\programs\python\python312\lib\site-packages (23.2.1)
Requirement already satisfied: setuptools in c:\users\root\appdata\local\programs\python\python312\lib\site-packages (68.2.2)
Requirement already satisfied: wheel in c:\users\root\appdata\local\programs\python\python312\lib\site-packages (0.41.2)

C:\proxy>py -m pip install -U --no-cache-dir --disable-pip-version-check -r requirements.txt
Ignoring uvloop: markers 'implementation_name == "cpython" and (sys_platform == "darwin" or sys_platform == "linux")' don't match your environment
Collecting aiodns<4,>=3.0 (from -r requirements.txt (line 1))
  Obtaining dependency information for aiodns<4,>=3.0 from https://files.pythonhosted.org/packages/61/1c/dc7a63e28cd4497ba05a3ff62684a49fd9d55c30671ca6f3f863ade0427a/aiodns-3.1.0-py3-none-any.whl.metadata
  Downloading aiodns-3.1.0-py3-none-any.whl.metadata (4.0 kB)
Collecting aiohttp-socks<0.9,>=0.7 (from -r requirements.txt (line 2))
  Obtaining dependency information for aiohttp-socks<0.9,>=0.7 from https://files.pythonhosted.org/packages/3f/81/cae77c14d88f5300b698c9ce39ae596605689b928495f1e66ec5648ad4b2/aiohttp_socks-0.8.4-py3-none-any.whl.metadata
  Downloading aiohttp_socks-0.8.4-py3-none-any.whl.metadata (3.1 kB)
Collecting aiohttp<4,>=3.8 (from -r requirements.txt (line 3))
  Downloading aiohttp-3.8.6.tar.gz (7.4 MB)
     ---------------------------------------- 7.4/7.4 MB 14.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: rich<14,>=12.3 in c:\users\root\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 4)) (13.6.0)
Collecting pycares>=4.0.0 (from aiodns<4,>=3.0->-r requirements.txt (line 1))
  Obtaining dependency information for pycares>=4.0.0 from https://files.pythonhosted.org/packages/d3/72/e6af5a0670eb0b5beadef95479387af22b0ed7088e180677be04bf076476/pycares-4.4.0-cp312-cp312-win_amd64.whl.metadata
  Downloading pycares-4.4.0-cp312-cp312-win_amd64.whl.metadata (4.5 kB)
Collecting python-socks[asyncio]<3.0.0,>=2.4.3 (from aiohttp-socks<0.9,>=0.7->-r requirements.txt (line 2))
  Obtaining dependency information for python-socks[asyncio]<3.0.0,>=2.4.3 from https://files.pythonhosted.org/packages/b2/16/6d7521041ceeb70344d5679a2367263840b8a983e547cc7f9e09b490e606/python_socks-2.4.3-py3-none-any.whl.metadata
  Downloading python_socks-2.4.3-py3-none-any.whl.metadata (7.1 kB)
Collecting attrs>=17.3.0 (from aiohttp<4,>=3.8->-r requirements.txt (line 3))
  Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
     ---------------------------------------- 61.2/61.2 kB ? eta 0:00:00
Collecting charset-normalizer<4.0,>=2.0 (from aiohttp<4,>=3.8->-r requirements.txt (line 3))
  Obtaining dependency information for charset-normalizer<4.0,>=2.0 from https://files.pythonhosted.org/packages/d1/47/148eae656ac376938afc97ed288893c6089038180c9e0782e5423ac0307d/charset_normalizer-3.3.0-cp312-cp312-win_amd64.whl.metadata
  Downloading charset_normalizer-3.3.0-cp312-cp312-win_amd64.whl.metadata (33 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.8->-r requirements.txt (line 3))
  Downloading multidict-6.0.4.tar.gz (51 kB)
     ---------------------------------------- 51.3/51.3 kB ? eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp<4,>=3.8->-r requirements.txt (line 3))
  Obtaining dependency information for async-timeout<5.0,>=4.0.0a3 from https://files.pythonhosted.org/packages/a7/fa/e01228c2938de91d47b307831c62ab9e4001e747789d0b05baf779a6488c/async_timeout-4.0.3-py3-none-any.whl.metadata
  Downloading async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp<4,>=3.8->-r requirements.txt (line 3))
  Downloading yarl-1.9.2.tar.gz (184 kB)
     ---------------------------------------- 184.7/184.7 kB ? eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting frozenlist>=1.1.1 (from aiohttp<4,>=3.8->-r requirements.txt (line 3))
  Downloading frozenlist-1.4.0.tar.gz (90 kB)
     ---------------------------------------- 90.7/90.7 kB ? eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiosignal>=1.1.2 (from aiohttp<4,>=3.8->-r requirements.txt (line 3))
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\root\appdata\roaming\python\python312\site-packages (from rich<14,>=12.3->-r requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\root\appdata\roaming\python\python312\site-packages (from rich<14,>=12.3->-r requirements.txt (line 4)) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\root\appdata\roaming\python\python312\site-packages (from markdown-it-py>=2.2.0->rich<14,>=12.3->-r requirements.txt (line 4)) (0.1.2)
Collecting cffi>=1.5.0 (from pycares>=4.0.0->aiodns<4,>=3.0->-r requirements.txt (line 1))
  Obtaining dependency information for cffi>=1.5.0 from https://files.pythonhosted.org/packages/e9/63/e285470a4880a4f36edabe4810057bd4b562c6ddcc165eacf9c3c7210b40/cffi-1.16.0-cp312-cp312-win_amd64.whl.metadata
  Downloading cffi-1.16.0-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp<4,>=3.8->-r requirements.txt (line 3))
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ---------------------------------------- 61.5/61.5 kB ? eta 0:00:00
Collecting pycparser (from cffi>=1.5.0->pycares>=4.0.0->aiodns<4,>=3.0->-r requirements.txt (line 1))
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ---------------------------------------- 118.7/118.7 kB ? eta 0:00:00
Downloading aiodns-3.1.0-py3-none-any.whl (5.3 kB)
Downloading aiohttp_socks-0.8.4-py3-none-any.whl (9.6 kB)
Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Downloading charset_normalizer-3.3.0-cp312-cp312-win_amd64.whl (98 kB)
   ---------------------------------------- 98.3/98.3 kB ? eta 0:00:00
Downloading pycares-4.4.0-cp312-cp312-win_amd64.whl (76 kB)
   ---------------------------------------- 76.3/76.3 kB ? eta 0:00:00
Downloading cffi-1.16.0-cp312-cp312-win_amd64.whl (181 kB)
   ---------------------------------------- 182.0/182.0 kB ? eta 0:00:00
Downloading python_socks-2.4.3-py3-none-any.whl (52 kB)
   ---------------------------------------- 52.4/52.4 kB ? eta 0:00:00
Building wheels for collected packages: aiohttp, frozenlist, multidict, yarl
  Building wheel for aiohttp (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for aiohttp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [110 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\abc.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\base_protocol.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\client.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\client_exceptions.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\client_proto.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\client_reqrep.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\client_ws.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\connector.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\cookiejar.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\formdata.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\hdrs.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\helpers.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\http.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\http_exceptions.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\http_parser.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\http_websocket.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\http_writer.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\locks.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\log.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\multipart.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\payload.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\payload_streamer.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\pytest_plugin.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\resolver.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\streams.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\tcp_helpers.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\test_utils.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\tracing.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\typedefs.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_app.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_exceptions.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_fileresponse.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_log.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_middlewares.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_protocol.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_request.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_response.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_routedef.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_runner.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_server.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_urldispatcher.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\web_ws.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\worker.py -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\__init__.py -> build\lib.win-amd64-cpython-312\aiohttp
      running egg_info
      writing aiohttp.egg-info\PKG-INFO
      writing dependency_links to aiohttp.egg-info\dependency_links.txt
      writing requirements to aiohttp.egg-info\requires.txt
      writing top-level names to aiohttp.egg-info\top_level.txt
      reading manifest file 'aiohttp.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'aiohttp' anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '*.lib' found anywhere in distribution
      warning: no previously-included files matching '*.dll' found anywhere in distribution
      warning: no previously-included files matching '*.a' found anywhere in distribution
      warning: no previously-included files matching '*.obj' found anywhere in distribution
      warning: no previously-included files found matching 'aiohttp\*.html'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE.txt'
      writing manifest file 'aiohttp.egg-info\SOURCES.txt'
      copying aiohttp\_cparser.pxd -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\_find_header.pxd -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\_headers.pxi -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\_helpers.pyi -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\_helpers.pyx -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\_http_parser.pyx -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\_http_writer.pyx -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\_websocket.pyx -> build\lib.win-amd64-cpython-312\aiohttp
      copying aiohttp\py.typed -> build\lib.win-amd64-cpython-312\aiohttp
      creating build\lib.win-amd64-cpython-312\aiohttp\.hash
      copying aiohttp\.hash\_cparser.pxd.hash -> build\lib.win-amd64-cpython-312\aiohttp\.hash
      copying aiohttp\.hash\_find_header.pxd.hash -> build\lib.win-amd64-cpython-312\aiohttp\.hash
      copying aiohttp\.hash\_helpers.pyi.hash -> build\lib.win-amd64-cpython-312\aiohttp\.hash
      copying aiohttp\.hash\_helpers.pyx.hash -> build\lib.win-amd64-cpython-312\aiohttp\.hash
      copying aiohttp\.hash\_http_parser.pyx.hash -> build\lib.win-amd64-cpython-312\aiohttp\.hash
      copying aiohttp\.hash\_http_writer.pyx.hash -> build\lib.win-amd64-cpython-312\aiohttp\.hash
      copying aiohttp\.hash\_websocket.pyx.hash -> build\lib.win-amd64-cpython-312\aiohttp\.hash
      copying aiohttp\.hash\hdrs.py.hash -> build\lib.win-amd64-cpython-312\aiohttp\.hash
      running build_ext
      building 'aiohttp._websocket' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\aiohttp
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\root\AppData\Local\Programs\Python\Python312\include -IC:\Users\root\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcaiohttp/_websocket.c /Fobuild\temp.win-amd64-cpython-312\Release\aiohttp/_websocket.obj
      _websocket.c
      aiohttp/_websocket.c(1475): warning C4996: 'Py_OptimizeFlag': deprecated in 3.12
      aiohttp/_websocket.c(3042): error C2039: "ob_digit": ­Ґ пў«пҐвбп з«Ґ­®¬ "_longobject".
      C:\Users\root\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note:  б¬. ®Ўкпў«Ґ­ЁҐ "_longobject"
      aiohttp/_websocket.c(3097): error C2039: "ob_digit": ­Ґ пў«пҐвбп з«Ґ­®¬ "_longobject".
      C:\Users\root\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note:  б¬. ®Ўкпў«Ґ­ЁҐ "_longobject"
      aiohttp/_websocket.c(3238): error C2039: "ob_digit": ­Ґ пў«пҐвбп з«Ґ­®¬ "_longobject".
      C:\Users\root\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note:  б¬. ®Ўкпў«Ґ­ЁҐ "_longobject"
      aiohttp/_websocket.c(3293): error C2039: "ob_digit": ­Ґ пў«пҐвбп з«Ґ­®¬ "_longobject".
      C:\Users\root\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note:  б¬. ®Ўкпў«Ґ­ЁҐ "_longobject"
      aiohttp/_websocket.c(3744): error C2039: "ob_digit": ­Ґ пў«пҐвбп з«Ґ­®¬ "_longobject".
      C:\Users\root\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note:  б¬. ®Ўкпў«Ґ­ЁҐ "_longobject"
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
  Building wheel for frozenlist (pyproject.toml) ... done
  Created wheel for frozenlist: filename=frozenlist-1.4.0-cp312-cp312-win_amd64.whl size=44783 sha256=3b4f90276487fac37408c17f53a24a9a1aea47426a82e73e913e44340e7403c6
  Stored in directory: C:\Temp\pip-ephem-wheel-cache-ppntbz4y\wheels\f1\9c\94\9386cb0ea511a93226456388d41d35f1c24ba15a62ffd7b1ef
  Building wheel for multidict (pyproject.toml) ... done
  Created wheel for multidict: filename=multidict-6.0.4-cp312-cp312-win_amd64.whl size=28212 sha256=17f3411c75d56abf7b64bc50226079082aadb78d246c2ae698282c27b00bcea8
  Stored in directory: C:\Temp\pip-ephem-wheel-cache-ppntbz4y\wheels\f6\d8\ff\3c14a64b8f2ab1aa94ba2888f5a988be6ab446ec5c8d1a82da
  Building wheel for yarl (pyproject.toml) ... done
  Created wheel for yarl: filename=yarl-1.9.2-cp312-cp312-win_amd64.whl size=59262 sha256=bef2d23ff4838c0d53a9a3f729084ef7e95fc50f152ee23c5d806614f32656de
  Stored in directory: C:\Temp\pip-ephem-wheel-cache-ppntbz4y\wheels\84\e3\6a\7d0fa1abee8e4aa39922b5bd54689b4b5e4269b2821f482a32
Successfully built frozenlist multidict yarl
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects

C:\proxy>py -m proxy_scraper_checker
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\proxy\proxy_scraper_checker\__main__.py", line 12, in <module>
    from .proxy_scraper_checker import ProxyScraperChecker
  File "C:\proxy\proxy_scraper_checker\proxy_scraper_checker.py", line 23, in <module>
    from aiohttp import ClientSession, ClientTimeout, DummyCookieJar
ModuleNotFoundError: No module named 'aiohttp'

**Comment by monosans** [comment]
aiohttp (the library required for this project) currently doesn't support Python 3.12.

You have two options:

1. Install Python 3.11
2. Install aiohttp beta by adding `--pre` flag to `pip install` in start.bat.
